### ISSUE TITLE
Alignments and colors are not preserving 

### ISSUE THREAD

**Issue by anurag16jun** [mwilliamson/java-mammoth#11]
While converting .docx file to html, I found that html document lacks alignment and color from docx file.

Trying converting  attached file with code,

String FILE1="Synopsis.docx";
[Synopsis.docx](https://github.com/mwilliamson/java-mammoth/files/2418585/Synopsis.docx)

DocumentConverter documentConverter = new DocumentConverter();
documentConverter.preserveEmptyParagraphs();
Result<String> stringResult= documentConverter.convertToHtml(new FileInputStream(new File(FILE1)));
FileOutputStream fileOutputStream = new FileOutputStream(new File("1.html"));
fileOutputStream.write(stringResult.getValue().getBytes(Charset.forName("UTF-16")));
fileOutputStream.close();

**Comment by mwilliamson** [comment]
Mammoth intentionally doesn't try to copy the exact formatting of the source document, and instead maps styles from Word to semantically marked up HTML (i.e. using tags and classes). If it's possible to use styles instead, then you can use a style map to map from Word styles to the appropriate HTML. If you want to copy the exact formatting, then I'm afraid Mammoth isn't the right tool for the job.
