### ISSUE TITLE
Please add Android compability

### ISSUE THREAD

**Issue by foobnix** [mwilliamson/java-mammoth#12]
Your great library can't be used with Android
Could you please add a few changes

1) Don't use javax.xml.stream.* (Please use external xml writer or your own XML writer) 
javax.xml.stream - not available in Android SDK

2) Make code compatible with JAVA 7 to support most of the devices on the market

Thank you,
I want to use your library in my reader but can't
https://github.com/foobnix/LibreraReader

**Comment by mwilliamson** [comment]
Unfortunately, I don't have the time to rewrite the codebase to support Java 7.

**Comment by foobnix** [comment]
Now it works for Android 8+ in my project
