### ISSUE TITLE
Getting the style of a text(alignment of text)

### ISSUE THREAD

**Issue by AshishBijlwan** [mwilliamson/java-mammoth#15]
Hi,
How can I get the alignment style of a text using mammoth?
eg: if I am aligning a text in the center of the docx file, after converting to HTML not getting the text in the center of the HTML page.

**Comment by mwilliamson** [comment]
Mammoth is designed to be used by mapping Word styles to the appropriate HTML, rather then exactly matching the formatting. For instance, if it's the case that some headings should be centred, such headings should have their own style that can then be mapped to a specified CSS class that can be styled appropriately,

If you're looking to copy the exact formatting of the source document, then Mammoth isn't the right tool for the job.
