### ISSUE TITLE
i try to use convertToHtml( docx file) method happens : error in opening zip file; 

### ISSUE THREAD

**Issue by gldegithub** [mwilliamson/java-mammoth#17]
at org.zwobble.mammoth.internal.archives.ZippedArchive.<init>(ZippedArchive.java:18)

**Comment by mwilliamson** [comment]
Could you provide the full stack trace and an example document? Does this happen with all documents, or just one? What happens if you create a blank document and try converting that?

**Comment by mwilliamson** [comment]
Closing since there's not much that can be done without more information.
