### ISSUE TITLE
java.io.IOException:Could not find main document part. Are you sure this is a valid .docx file?

### ISSUE THREAD

**Issue by d470969047h** [mwilliamson/java-mammoth#18]
The above problem occurred when I was reading the file in MongoDB.
I called the  "converter.convertToHtml(inputstream)" method,and MongoDB inputstream type is GridFSDownloadStream. 
I saved the MongoDB file locally before reading it, and the file can be opened from Word.But there was still a problem “java.util.zip.ZipException:error in opening zip file”

**Comment by mwilliamson** [comment]
Could you provide an example document?

**Comment by d470969047h** [comment]
I found that I could only extract the contents of the.docx file,if it's a.doc file, it's not supported

**Comment by mwilliamson** [comment]
Mammoth only supports docx files, so if you only have trouble with doc files, then I don't think there's an issue.

**Comment by d470969047h** [comment]
Ok, so think about supporting .doc later?

**Comment by mwilliamson** [comment]
I'm afraid there's no plan to support .doc files.
