### ISSUE TITLE
An unrecognised element was ignored: v:oval

### ISSUE THREAD

**Issue by saranraju** [mwilliamson/java-mammoth#20]
Using Mammoth 1.4.1 jar

Getting the following error
[An unrecognised element was ignored: v:path, An unrecognised element was ignored: v:oval, An unrecognised element was ignored: v:stroke]
[test1.docx](https://github.com/mwilliamson/java-mammoth/files/4890517/test1.docx)

**Comment by mwilliamson** [comment]
Mammoth doesn't support VML images, I'm afraid.
