### ISSUE TITLE
Alignment and list alingment

### ISSUE THREAD

**Issue by greypeg** [mwilliamson/java-mammoth#22]
Hi,
I am testing your api in order to use it and I try to convert a word file to html. One major thing is that it doesn't make any general text alignment changes (for instance Left - Center - Right) and the Lists of word (for instance: 

- dog 
   - cat 
   - bird
)

have some sort of alignment but the api doesn't make any changes either.
Is there a way for me to make the api do those things ??

**Comment by mwilliamson** [comment]
Mammoth maps styles in Word to the appropriate HTML with CSS classes. It will ignore other formatting such as alignment. I'd suggest using styles with the appropriate alignment rather than applying the alignment directly to the text. The Word style can then be mapped to HTML using a style mapping.
