### ISSUE TITLE
Maintain spacing B/W Two Paragraph. 

### ISSUE THREAD

**Issue by VaibhavGupta982** [mwilliamson/java-mammoth#26]
I am trying to convert Doc to HTML through mammoth java Lib. but it removes the spacing BW two paragraph. I found some suggestions "var options = {
    styleMap: [
      "p[style-name='center'] => center",
      "p[style-name='Heading 1'] => p:fresh > h1:fresh",
      "p[style-name='Heading 2'] => p:fresh > h2:fresh",
      "p[style-name='Heading 3'] => p:fresh > h3:fresh",
      "p[style-name='Heading 4'] => p:fresh > h4:fresh",
      "p[style-name='Heading 5'] => p:fresh > h5:fresh",
      "p[style-name='Heading 6'] => p:fresh > h6:fresh"
    ],
    transformDocument: transformElement,
    ignoreEmptyParagraphs: false
  }; "  and "DocumentConverter converter = new DocumentConverter().preserveEmptyParagraphs();"
to maintain the spaceing. but it is not working. can someone suggest me if I am doing something wrong.

> @mwilliamson 
[tablecheck.docx](https://github.com/mwilliamson/java-mammoth/files/6575107/tablecheck.docx)

![IMG-eab356043d4630e86bd757dd1dd28791-V](https://user-images.githubusercontent.com/51715975/120301969-0613dc00-c2eb-11eb-920f-b78921f0da9c.jpg)

This is docx 

![IMG-2ba3a043cd195639bd885156fa497c9e-V](https://user-images.githubusercontent.com/51715975/120302022-12983480-c2eb-11eb-8ace-e49a4bd57eab.jpg)

This is html

**Comment by mwilliamson** [comment]
In general, Mammoth isn't designed to directly reproduce the exact spacing of the original document. If the paragraphs are empty with zero height, then I'd assume that the margins collapse, causing the result you're seeing. If you want to give the empty paragraphs some height, that's something you can address in your CSS.

**Comment by VaibhavGupta982** [comment]
Hello, sir
Can you please suggest me how can I address CSS in java mammoth library.

**Comment by mwilliamson** [comment]
Once the HTML has been generated, styling it with CSS is independent of Mammoth. Exactly how you want to include the fragment generated by Mammoth in a full HTML page, and how you want to style it, isn't something I can help with, I'm afraid.
