### ISSUE TITLE
Add fontsize during conversion from docx to html

### ISSUE THREAD

**Issue by welaine111** [mwilliamson/java-mammoth#27]
Hi, 
we want to extract the font size in the docx file and convert it to html <font size=""> element.
I see in your js version of mammoth, 
there is a bug:https://github.com/mwilliamson/mammoth.js/issues/109 which ppl found how to add color.
And in your js version file: https://github.com/mwilliamson/mammoth.js/blob/master/lib/documents.js
In your Run method, you have properties.fontSize I assume if I follow the bug109, I can apply the font size to my converted html?

How can we do it in the java version of Mammoth?

**Comment by mwilliamson** [comment]
Mammoth intentionally doesn't copy the formatted of the source document, so copying the exact font size isn't something that will be supported. If you want to use Mammoth, I'd suggest applying an appropriate style and writing a style map instead.
