### ISSUE TITLE
Image converter add attribute id  or class 

### ISSUE THREAD

**Issue by gowelaine** [mwilliamson/java-mammoth#28]
Hi,
Is it possible to add attribute id or class on img tag during the ImageConverter process? 
So it's easy to identify each image after converter is done. for instance,

 [image id="image-vangogh"   src="/img/html/vangogh.jpg" alt="Van Gogh, Self-portrait"]
Right now it seems only alt and src can be generated.

**Comment by mwilliamson** [comment]
I believe you should be able to supply any attributes from the image converter, including IDs and class names, which will be included in the outputted HTML.
