### ISSUE TITLE
Get list of pages instead of one html string

### ISSUE THREAD

**Issue by d4nielix** [mwilliamson/java-mammoth#34]
Hi, I have tried to achieve a list of strings instead of one string with the HTML of the whole document. Is there a way to do this like converting every page as a different string in a list? It could be divided by pages, or headings, etc. 

So instead of:
`final String html = result.getValue();`

I would like to have:
`final List<String> html = result.getValue();`

**Comment by mwilliamson** [comment]
I reckon splitting by pages is outside of the scope of Mammoth. For splitting by heading: I'd suggest the simplest thing to do would be to use a post-processing step on the HTML that's outputted.
