### ISSUE TITLE
The font display in Webview is too small, how can I change to a larger size?

### ISSUE THREAD

**Issue by NanyangTaiji** [mwilliamson/java-mammoth#36]
If you're reporting a bug or requesting a feature, please include:
* a minimal example document
* the HTML output that you'd expect

If you're reporting a bug, it's also useful to know what platform you're
running on, including:

* the version of the JVM
* the version of Java, or other language that you're using
* the operating system and version

**Comment by mwilliamson** [comment]
If the correct HTML is being produced, then this sounds like you'll want to update the CSS you're applying to the page. Since that's separate from the HTML that Mammoth generates, I'm closing this.
