### ISSUE TITLE
Template might not exists or might nor be accessible by ano of the configured template resolvers

### ISSUE THREAD

**Issue by FaheemBhatti** [mwilliamson/java-mammoth#37]
If you're reporting a bug or requesting a feature, please include:
* a minimal example document
* the HTML output that you'd expect

If you're reporting a bug, it's also useful to know what platform you're
running on, including:

* the version of the JVM
* the version of Java, or other language that you're using
* the operating system and version

![image](https://user-images.githubusercontent.com/50632975/235730235-8cad24e0-8716-4da4-b9ac-7c06ff4c8c9a.png)

![image](https://user-images.githubusercontent.com/50632975/235730349-872b0b93-4367-4cd0-98fd-bf611277c0bf.png)

I am all the time getting this exception, can you please provide a helping example or a solution

**Comment by mwilliamson** [comment]
That looks like an issue with whatever web library or framework you're using. It seems as though the return value should be the name of a template rather than a string of HTML. Assuming the value of `html` is indeed the HTML you'd expect, then I'm afraid I can't help.
