### ISSUE TITLE
Charset not set to UTF-8 throughout the project

### ISSUE THREAD

**Issue by jasonmarco** [mwilliamson/java-mammoth#38]
I am receiving the below RuntimeException when running Maven tests: 

> embeddedStyleMapCanBeWrittenAndThenRead()  Time elapsed: 0.002 sec  <<< ERROR!
> java.lang.RuntimeException: javax.xml.stream.XMLStreamException: Underlying stream encoding 'Cp1252' and input paramter for writeStartDocument() method 'UTF-8' do not match.
>         at org.zwobble.mammoth.tests.MammothTests.embeddedStyleMapCanBeWrittenAndThenRead(MammothTests.java:291)
> Caused by: javax.xml.stream.XMLStreamException: Underlying stream encoding 'Cp1252' and input paramter for writeStartDocument() method 'UTF-8' do not match.
>         at org.zwobble.mammoth.tests.MammothTests.embeddedStyleMapCanBeWrittenAndThenRead(MammothTests.java:291)

There are some streams that are missing charset configurations, this causes the JDK to fall back to the default charset. In my particular case, the JDK determines the default charset to be 'cp1252' which differs from the hard coded UTF-8 encodings used throughout most of the project. Explicitly setting the encoding to UTF-8 everywhere will resolve this mismatch.

Operating System:
- Microsoft Windows 10
- 10.0.19044 N/A Build 19044

JDK:
- openjdk 17.0.6 2023-01-17 LTS
- OpenJDK Runtime Environment (build 17.0.6+10-LTS)
- OpenJDK 64-Bit Server VM (build 17.0.6+10-LTS, mixed mode, sharing)

**Comment by mwilliamson** [comment]
Thanks for the report. Is that the full stack trace you get when you get the exception?

**Comment by jasonmarco** [comment]
No problem, thanks for taking a look.

Please see attached SureFire reports:

[TEST-org.zwobble.mammoth.tests.docx.DocumentReaderTests.xml.txt](https://github.com/mwilliamson/java-mammoth/files/11939813/TEST-org.zwobble.mammoth.tests.docx.DocumentReaderTests.xml.txt)
[TEST-org.zwobble.mammoth.tests.docx.EmbeddedStyleMapTests.xml.txt](https://github.com/mwilliamson/java-mammoth/files/11939814/TEST-org.zwobble.mammoth.tests.docx.EmbeddedStyleMapTests.xml.txt)
[TEST-org.zwobble.mammoth.tests.MammothTests.xml.txt](https://github.com/mwilliamson/java-mammoth/files/11939815/TEST-org.zwobble.mammoth.tests.MammothTests.xml.txt)

I submitted PR GH-39 that should fix this.

**Comment by mwilliamson** [comment]
This should be fixed in master now. Thanks again!
