### ISSUE TITLE
cannot access org.zwobble.mammoth.DocumentConverter

### ISSUE THREAD

**Issue by sutmr** [mwilliamson/java-mammoth#5]
run  with  the compile error:cannot access org.zwobble.mammoth.DocumentConverter

**Comment by mwilliamson** [comment]
I'm afraid there's not really enough information for me to be able to help you. The latest JAR from Maven Central looked okay from a quick glance. If you find anything wrong with the published artefacts, let me know and I'll take a look.

**Comment by mwilliamson** [comment]
Closing since there's nothing I can do without more information.
