### ISSUE TITLE
how to use it under jdk1.7

### ISSUE THREAD

**Issue by sutmr** [mwilliamson/java-mammoth#6]
the lib is very useful , but I have to use it under the jdk1.7 version , Can you give some suggestion?  
many thanks!

**Comment by mwilliamson** [comment]
The code relies on features from Java 8, so Java 7 isn't supported. There are some tools that can rewrite the bytecode to be compatible with Java 7, but I'm not sure whether Mammoth also relies on any parts of the standard library.
