### ISSUE TITLE
Mammoth is unable to parse page header content in .docx file

### ISSUE THREAD

**Issue by Zubin-Sachdeva** [mwilliamson/java-mammoth#9]
Hi,
I was using tika parser earlier to convert word to HTML, but tika had this limitation that it couldn't parse the lists and the superscript in the word doc. Mammoth works like a charm, but the only issue I'm facing is that it is not able to parse the page header at all. Even rawText is not giving me the header content. Would you please comment on whether it is possible to do the same in mammoth?

**Comment by mwilliamson** [comment]
Headers are currently ignored by Mammoth.
